export const blogTags = [
  "Travel",
  "Artificial Intelligence",
  "Food & Cooking",
  "Cybersecurity",
  "Lifestyle",
  "Machine Learning",
  "Personal Development",
  "E-Commerce",
  "Fitness & Wellness",
  "Quantum Computing",
  "Home Decor",
  "Digital Nomads",
  "Mental Health",
  "Gardening",
  "Blockchain",
  "Arts & Crafts",
  "Climate Change",
  "Freelancing",
  "Parenting Tips",
  "Sustainable Living",
  "Gaming Industry",
  "Influencer Marketing",
  "5G Technology",
  "Self-Care",
  "Data Privacy",
  "Cultural Insights",
  "HealthTech",
  "Virtual Reality",
  "Mindfulness",
  "Web Development",
  "Digital Marketing",
  "SaaS (Software as a Service)",
  "Startup Culture",
  "Books & Literature",
  "Social Media",
  "Hobbies & Interests",
  "EdTech (Education Technology)",
  "Electric Vehicles",
  "Pet Care",
  "Augmented Reality",
  "Cloud Computing",
  "Career Development",
  "Green Technology"
];
